version: 2.1
jobs:
  build:
    working_directory: ~/scala-rbac
    docker:
      - image: mozilla/sbt:8u232_1.4.5
    steps:
      - checkout
      - run:
          name: Test
          command: |
            RUN apt-get install -y curl \
              && curl -sL https://deb.nodesource.com/setup_9.x | bash - \
              && apt-get install -y nodejs \
              && curl -L https://www.npmjs.com/install.sh | sh
            
            sbt "+test" || sbt 'last ProjectRef(uri("file:/root/scala-rbac/"), "rbacCoreJS") / Test / loadedTestFrameworks'