version: 2.1
jobs:
  build:
    docker:
      - image: mozilla/sbt:8u232_1.4.5
    steps:
      - checkout
      - run:
          name: Test
          command: |
            ls -la
            sbt "+test"