version: 2.1
jobs:
  build:
    working_directory: ~/scala-rbac
    docker:
      - image: mozilla/sbt:8u232_1.4.5
    steps:
      - checkout
      - run:
          name: Test
          command: |
            sbt "+test" || sbt 'last ProjectRef(uri("file:/root/scala-rbac/"), "rbacCoreJS") / Test / loadedTestFrameworks'